from . import ir_module
from . import res_config_settings
from . import thailand_compliance_payroll_common
from . import thailand_pnd1_attachment_common
from . import thailand_pnd1_month
from . import thailand_pnd1_year_company
from . import thailand_withholding_tax_certificate
from . import thailand_sps1_10
from . import thailand_SPS1_10_company
from . import hr_payroll_report_income_type
from . import hr_salary_rule
from . import hr_payslip
