{
    "name": "Thai Compliance for Payroll Module",
    "version": "15.0.4.0.0",
    "summary": "Social security and revenue department document management.",
    "category": "Human resources",
    "author": "Louis de Gislain de Bontin",
    "company": "Newlogic",
    "website": "https://www.newlogic.com",
    "depends": [
        "hr",
        "hr_payroll",
        "thai_compliance",
        "hr_social_security_misc",
        "hr_employee_withholding_tax_th",
        "hr_employee_compose_name",
    ],
    "data": [
        "security/ir.model.access.csv",
        #
        "views/menu.xml",
        "views/hr_payroll_report_income_type_views.xml",
        "views/pnd1_month_views.xml",
        "views/pnd1_year_company_views.xml",
        "views/withholding_tax_certificate_views.xml",
        "views/sps1_10_views.xml",
        "views/sps1_10_company_views.xml",
        "views/res_config_settings_views.xml",
        "views/hr_payroll_structure_type_views.xml",
    ],
    "license": "Other proprietary",
    "installable": True,
    "auto_install": False,
    "application": True,
    "post_init_hook": "test_post_init_hook",
}
